name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kharutta
          filename: github-metrics-calendar.svg
          plugin_calendar: yes
          plugin_calendar_limit: 365

  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kharutta
          filename: github-metrics-languages.svg
          plugin_languages: yes
          plugin_languages_details: percentage, bytes-size
          plugin_languages_limit: 5 

  isocalendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kharutta
          filename: github-metrics-isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
